[package]
name = "traffic-flow-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
rocket_okapi = {version = "0.9.0", features = ["swagger"]}
schemars = "0.8.22"
serde = {version = "1.0", features = ["derive"]}
sqlx = "0.8.3"

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_mysql"]
