name: Frontend Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash
    - name: Add Bun to PATH
      run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
    - run: |
        cd frontend
        bun install
        bun test
